# Arrays

Numpy arrays mostly the same as python arrays
<br>Only Difference is multi arrays


Can help reducing storage and increase performance

In [6]:
import numpy as np
a = np.array([1, 2, 3, 4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a.dtype
#to get the data type of an np element use .dtype

dtype('int32')

In [5]:
#to change the data type of an array just add it in the array decliration
b = np.array([1, 2, 3, 4], dtype=np.int64)
b.dtype

dtype('int64')

# Arrays with calculations

In [7]:
#In numpy you can temp change arrays but it will not permanently modify the array as shown below
a + 10

array([11, 12, 13, 14])

In [8]:
a * 10

array([10, 20, 30, 40])

In [9]:
a

array([1, 2, 3, 4])

As shown the array can have the above calculations done but as shown by the last statement the original array hasn't been changed

With the above calculations that can be done with numpy, they can also be used to add arrays to eachother as shown

In [10]:
b = np.array([2, 4, 6, 8])

In [11]:
a + b

array([ 3,  6,  9, 12])

# Boolean Arrays

In [14]:
a

array([1, 2, 3, 4])

In [13]:
a[[True, True, False, True]]

array([1, 2, 4])

In [15]:
a <= 3

array([ True,  True,  True, False])

In [16]:
a.mean()

2.5

In [17]:
a[a <= 3]

array([1, 2, 3])

In [25]:
a[~1]

3

### 2D array boolean

In [28]:
b = np.array([
    [2, 6, 3],
    [9, 10, 1],
    [3, 5, 15]
])
b

array([[ 2,  6,  3],
       [ 9, 10,  1],
       [ 3,  5, 15]])

Can be used on 3d arrays as well as shown below which allows for filtering

In [29]:
b[b < 5]

array([2, 3, 1, 3])